### ISSUE TITLE
Multiple charts using document.getelementsbyclassname

### ISSUE THREAD

**Issue by kritsky** [kbychkov/dailychart#6]
I was trying this:
`new Dailychart(document.getelementsbyclassname('chart'), {`

But i've got the error:

> Uncaught TypeError: t.getAttribute is not a function

How to do that? Thanks

**Comment by kbychkov** [comment]
Hello! The constructor doesn't accept an array at the moment. You could use a `for` loop to initialize every element. It would be a good feature for the next release though. Thanks for the hint.

**Comment by kritsky** [comment]
Thanks
